# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 622)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("mainicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadTaskHostsButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.loadTaskHostsButton.setIconSize(QtCore.QSize(24, 24))
        self.loadTaskHostsButton.setObjectName("loadTaskHostsButton")
        self.horizontalLayout.addWidget(self.loadTaskHostsButton)
        self.loadCommandsButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.loadCommandsButton.setMaximumSize(QtCore.QSize(16777215, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/tasks-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadCommandsButton.setIcon(icon1)
        self.loadCommandsButton.setIconSize(QtCore.QSize(24, 24))
        self.loadCommandsButton.setObjectName("loadCommandsButton")
        self.horizontalLayout.addWidget(self.loadCommandsButton)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setMaximumSize(QtCore.QSize(16777215, 41))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/linux-terminal-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton.setIcon(icon2)
        self.commandLinkButton.setIconSize(QtCore.QSize(24, 24))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.horizontalLayout.addWidget(self.commandLinkButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hostsTable = QtWidgets.QTableWidget(self.centralwidget)
        self.hostsTable.setMinimumSize(QtCore.QSize(200, 0))
        self.hostsTable.setObjectName("hostsTable")
        self.hostsTable.setColumnCount(2)
        self.hostsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.hostsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hostsTable.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_2.addWidget(self.hostsTable)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listCommands = QtWidgets.QListWidget(self.centralwidget)
        self.listCommands.setMaximumSize(QtCore.QSize(16777215, 200))
        self.listCommands.setObjectName("listCommands")
        self.verticalLayout_3.addWidget(self.listCommands)
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setBaseSize(QtCore.QSize(0, 0))
        self.mdiArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.mdiArea.setViewMode(QtWidgets.QMdiArea.SubWindowView)
        self.mdiArea.setDocumentMode(False)
        self.mdiArea.setTabsClosable(False)
        self.mdiArea.setTabsMovable(False)
        self.mdiArea.setObjectName("mdiArea")
        self.verticalLayout_3.addWidget(self.mdiArea)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1011, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.loadCommandsAction = QtWidgets.QAction(MainWindow)
        self.loadCommandsAction.setObjectName("loadCommandsAction")
        self.saveCommandsAction = QtWidgets.QAction(MainWindow)
        self.saveCommandsAction.setObjectName("saveCommandsAction")
        self.clearCommandsAction = QtWidgets.QAction(MainWindow)
        self.clearCommandsAction.setObjectName("clearCommandsAction")
        self.loadTaskHostsAction = QtWidgets.QAction(MainWindow)
        self.loadTaskHostsAction.setObjectName("loadTaskHostsAction")
        self.clearHostsAction = QtWidgets.QAction(MainWindow)
        self.clearHostsAction.setObjectName("clearHostsAction")
        self.aboutAction = QtWidgets.QAction(MainWindow)
        self.aboutAction.setObjectName("aboutAction")
        self.menu.addAction(self.loadCommandsAction)
        self.menu.addAction(self.saveCommandsAction)
        self.menu.addAction(self.clearCommandsAction)
        self.menu_2.addAction(self.loadTaskHostsAction)
        self.menu_2.addAction(self.clearHostsAction)
        self.menu_3.addAction(self.aboutAction)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Linux Remote Master"))
        self.loadTaskHostsButton.setText(_translate("MainWindow", "Загрузить список хостов"))
        self.loadCommandsButton.setText(_translate("MainWindow", "Загрузить команды"))
        self.commandLinkButton.setText(_translate("MainWindow", "Выполнить"))
        item = self.hostsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Хост"))
        item = self.hostsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP"))
        self.menu.setTitle(_translate("MainWindow", "Команды"))
        self.menu_2.setTitle(_translate("MainWindow", "Хосты"))
        self.menu_3.setTitle(_translate("MainWindow", "Справка"))
        self.loadCommandsAction.setText(_translate("MainWindow", "Загрузить..."))
        self.saveCommandsAction.setText(_translate("MainWindow", "Сохранить..."))
        self.clearCommandsAction.setText(_translate("MainWindow", "Очистить"))
        self.loadTaskHostsAction.setText(_translate("MainWindow", "Загрузить список..."))
        self.clearHostsAction.setText(_translate("MainWindow", "Очистить список"))
        self.aboutAction.setText(_translate("MainWindow", "О программе..."))
